import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/index.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>niccannon.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello, world</h1>
      </main>

      <footer>Nicholas Cannon</footer>
    </>
  );
};

export default Home;
